#nullable enable

using System.IO;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;

namespace Docxodus.Tests;

/// <summary>
/// Deterministic builder for the vendored comment-dense fixture
/// (<c>TestFiles/DD/DD002-DenseComments.docx</c>). The in-repo, license-clean, reproducible source-of-truth
/// for that committed artifact: a small contract carrying the non-coincidental comment shapes a real
/// reviewed contract exposes — a paragraph with MULTIPLE comments, OVERLAPPING ranges, a range SPANNING
/// paragraphs, a comment whose anchored text is itself edited, a THREADED reply
/// (<c>commentsExtended</c> <c>paraIdParent</c>), and plain commented sentences — so the comment
/// id↔range↔reference↔definition + threading oracles in <see cref="DocxDiffCommentRealDocTests"/> run on
/// every build without depending on any machine-local file.
/// <para>The committed .docx is regenerated by <c>DocxDiffCommentRealDocTests.__RegenerateVendoredFixture</c>
/// (a Skip-by-default fact). Keep this builder and that file in sync.</para>
/// </summary>
public static class DocxDiffCommentRealDocFixture
{
    private const string W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
    private const string W14 = "http://schemas.microsoft.com/office/word/2010/wordml";
    private const string W15 = "http://schemas.microsoft.com/office/word/2012/wordml";
    private const string R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";

    /// <summary>Build the dense comment fixture as in-memory DOCX bytes. Deterministic (no timestamps in content).</summary>
    public static byte[] Build()
    {
        using var ms = new MemoryStream();
        using (var doc = WordprocessingDocument.Create(ms, WordprocessingDocumentType.Document))
        {
            var main = doc.AddMainDocumentPart();
            WritePartXml(main.AddNewPart<StyleDefinitionsPart>(), StylesXml());
            WritePartXml(main.AddNewPart<DocumentSettingsPart>(), $"<w:settings xmlns:w=\"{W}\"/>");
            WritePartXml(main.AddNewPart<WordprocessingCommentsPart>(), CommentsXml());
            WritePartXml(main.AddNewPart<WordprocessingCommentsExPart>(), CommentsExXml());
            WritePartXml(main, DocumentXml());
        }
        return ms.ToArray();
    }

    // ---- fragment helpers -----------------------------------------------------------------------

    private static string Run(string text) => $"<w:r><w:t xml:space=\"preserve\">{text}</w:t></w:r>";
    private static string Open(string id) => $"<w:commentRangeStart w:id=\"{id}\"/>";
    private static string Close(string id) => $"<w:commentRangeEnd w:id=\"{id}\"/>";
    private static string RefRun(string id) =>
        $"<w:r><w:rPr><w:rStyle w:val=\"CommentReference\"/></w:rPr><w:commentReference w:id=\"{id}\"/></w:r>";

    private static string Cmt(string id, string author, string text, string paraId) =>
        $"<w:comment w:id=\"{id}\" w:author=\"{author}\" w:date=\"2020-01-01T00:00:00Z\" w:initials=\"{author[0]}\">" +
        $"<w:p w14:paraId=\"{paraId}\"><w:r><w:t xml:space=\"preserve\">{text}</w:t></w:r></w:p></w:comment>";

    private static string CmtEx(string paraId, string? parent) =>
        $"<w15:commentEx w15:paraId=\"{paraId}\"{(parent != null ? $" w15:paraIdParent=\"{parent}\"" : "")} w15:done=\"0\"/>";

    // ---- parts ----------------------------------------------------------------------------------

    private static string StylesXml() =>
        $"<w:styles xmlns:w=\"{W}\">" +
        "<w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii=\"Times New Roman\" w:hAnsi=\"Times New Roman\"/>" +
        "<w:sz w:val=\"24\"/><w:szCs w:val=\"24\"/></w:rPr></w:rPrDefault></w:docDefaults>" +
        "<w:style w:type=\"paragraph\" w:default=\"1\" w:styleId=\"Normal\"><w:name w:val=\"Normal\"/></w:style>" +
        "<w:style w:type=\"paragraph\" w:styleId=\"Heading1\"><w:name w:val=\"heading 1\"/>" +
        "<w:basedOn w:val=\"Normal\"/><w:pPr><w:outlineLvl w:val=\"0\"/></w:pPr><w:rPr><w:b/><w:sz w:val=\"28\"/></w:rPr></w:style>" +
        "<w:style w:type=\"character\" w:styleId=\"CommentReference\"><w:name w:val=\"annotation reference\"/></w:style>" +
        "</w:styles>";

    private static string CommentsXml() =>
        $"<w:comments xmlns:w=\"{W}\" xmlns:w14=\"{W14}\">" +
        Cmt("0", "Alice", "scope of the recitals", "10000001") +
        Cmt("1", "Bob", "confirm the parties list", "10000002") +
        Cmt("2", "Carol", "covers the definition and the term", "10000003") +
        Cmt("3", "Dan", "covers the term and its scope", "10000004") +
        Cmt("4", "Erin", "this obligation spans the clause", "10000005") +
        Cmt("5", "Frank", "is this the right indemnity cap?", "10000006") +
        Cmt("6", "Grace", "should we keep the survival period?", "10000007") +
        Cmt("7", "Heidi", "agree, keep it as drafted", "10000008") +
        Cmt("8", "Ivan", "check governing law", "10000009") +
        Cmt("9", "Judy", "verify the notice address", "1000000A") +
        "</w:comments>";

    private static string CommentsExXml() =>
        $"<w15:commentsEx xmlns:w=\"{W}\" xmlns:w15=\"{W15}\">" +
        CmtEx("10000001", null) + CmtEx("10000002", null) + CmtEx("10000003", null) + CmtEx("10000004", null) +
        CmtEx("10000005", null) + CmtEx("10000006", null) +
        CmtEx("10000007", null) +            // parent: survival-period question
        CmtEx("10000008", "10000007") +      // reply to the survival-period question
        CmtEx("10000009", null) + CmtEx("1000000A", null) +
        "</w15:commentsEx>";

    private static string DocumentXml() =>
        $"<w:document xmlns:w=\"{W}\" xmlns:r=\"{R}\" xmlns:w14=\"{W14}\"><w:body>" +
        // heading
        "<w:p><w:pPr><w:pStyle w:val=\"Heading1\"/></w:pPr><w:r><w:t>Master Agreement</w:t></w:r></w:p>" +
        // 1. a paragraph carrying TWO comments on different phrases
        "<w:p><w:r><w:t xml:space=\"preserve\">These </w:t></w:r>" +
        Open("0") + Run("recitals") + Close("0") + RefRun("0") +
        "<w:r><w:t xml:space=\"preserve\"> bind the </w:t></w:r>" +
        Open("1") + Run("parties named below") + Close("1") + RefRun("1") +
        "<w:r><w:t xml:space=\"preserve\"> on the effective date.</w:t></w:r></w:p>" +
        // 2. overlapping ranges over "definition term scope"
        "<w:p><w:r><w:t xml:space=\"preserve\">The </w:t></w:r>" +
        Open("2") + Run("definition ") + Open("3") + Run("term") + Close("2") + Run(" scope") + Close("3") +
        RefRun("2") + RefRun("3") +
        "<w:r><w:t xml:space=\"preserve\"> is controlling here.</w:t></w:r></w:p>" +
        // 3. a range SPANNING two paragraphs (id 4)
        "<w:p>" + Open("4") + Run("Each obligation under this clause is several.") + "</w:p>" +
        "<w:p>" + Run("It continues until performance is complete.") + Close("4") + RefRun("4") + "</w:p>" +
        // 4. a comment whose anchored word will be edited (id 5)
        "<w:p><w:r><w:t xml:space=\"preserve\">The indemnity </w:t></w:r>" +
        Open("5") + Run("cap") + Close("5") + RefRun("5") +
        "<w:r><w:t xml:space=\"preserve\"> applies to all claims.</w:t></w:r></w:p>" +
        // 5. a THREADED comment (parent 6 + reply 7) whose anchored phrase will be edited
        "<w:p><w:r><w:t xml:space=\"preserve\">The </w:t></w:r>" +
        Open("6") + Run("survival period") + Close("6") + RefRun("6") + RefRun("7") +
        "<w:r><w:t xml:space=\"preserve\"> is two years from closing.</w:t></w:r></w:p>" +
        // 6. plain commented sentences (8, 9)
        "<w:p>" + Open("8") + Run("This Agreement is governed by Delaware law.") + Close("8") + RefRun("8") + "</w:p>" +
        "<w:p>" + Open("9") + Run("Notices go to the address on the signature page.") + Close("9") + RefRun("9") + "</w:p>" +
        "<w:sectPr><w:pgSz w:w=\"12240\" w:h=\"15840\"/></w:sectPr></w:body></w:document>";

    private static void WritePartXml(OpenXmlPart part, string xml)
    {
        using var stream = part.GetStream(FileMode.Create, FileAccess.Write);
        using var writer = new StreamWriter(stream, new System.Text.UTF8Encoding(false));
        writer.Write(xml);
    }
}
