#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Validation;
using DocumentFormat.OpenXml.Wordprocessing;
using Docxodus;
using Xunit;
using Xunit.Abstractions;

namespace Docxodus.Tests;

/// <summary>
/// Headline real-document verification of bookmark / internal cross-reference / footnote / endnote fidelity.
/// The always-run case is the vendored dense fixture <c>TestFiles/DD/DD001-DenseBookmarkXrefFootnote.docx</c>
/// (built by <see cref="DocxDiffRealDocFixture"/>): a Series-A-style contract carrying bookmarked defined terms
/// and sections, REF/PAGEREF/NOTEREF fields and an internal hyperlink anchor pointing back at them, footnotes
/// (one of which cites another — a note-in-note reference), endnotes, and non-sequential footnote ids. The
/// optional cases additionally exercise the much denser NVCA model contracts (COI: ~392 bookmarks / 82 REF
/// fields / 111 footnotes; SPA: ~192 bookmarks / 68 REF fields) when those files are present on the machine.
/// <para>For each document a variant is produced by editing many bookmark-BEARING and bookmark-REFERENCING
/// paragraphs, then <see cref="DocxDiff.Compare"/> must hold the structural id↔name↔reference invariants, the
/// body-text + bookmark-structure + note-text round-trip (accept ≡ right, reject ≡ left), and emit a document
/// with no NEW schema errors. The vendored fixture is REQUIRED (a missing/empty file fails the suite — that is
/// the CI-durable guarantee); the NVCA cases soft-skip when absent so the suite stays portable.</para>
/// </summary>
public class DocxDiffBookmarkRealDocTests
{
    private readonly ITestOutputHelper _out;
    public DocxDiffBookmarkRealDocTests(ITestOutputHelper o) => _out = o;

    private static readonly DirectoryInfo TestFilesDir = new("../../../../TestFiles/");

    /// <summary>The vendored dense fixture, regenerated by <see cref="__RegenerateVendoredFixture"/>.</summary>
    public static string VendoredFixturePath =>
        Path.Combine(TestFilesDir.FullName, "DD", "DD001-DenseBookmarkXrefFootnote.docx");

    // (path, tag, required). The vendored fixture is REQUIRED — it must be committed and run in CI. The NVCA
    // model contracts are OPTIONAL local enrichment: a far denser real-world stress that runs when present.
    public static IEnumerable<object[]> Contracts() => new[]
    {
        new object[] { VendoredFixturePath, "dense", true },
        new object[] { "/home/jman/Downloads/NVCA-Model-COI-10-1-2025.docx", "coi", false },
        new object[] { "/home/jman/Downloads/NVCA-Model-SPA-10-28-2025-1.docx", "spa", false },
    };

    private static readonly string ScratchDir =
        Path.Combine(Path.GetTempPath(), "docxodus-realdoc-fidelity");

    [Theory]
    [MemberData(nameof(Contracts))]
    public void Contract_BookmarkAndCrossReferenceFidelity(string path, string tag, bool required)
    {
        if (!File.Exists(path) || new FileInfo(path).Length == 0)
        {
            // The vendored fixture is the CI-durable guarantee: a missing/empty committed artifact is a failure,
            // NOT a portable no-op. The optional NVCA contracts soft-skip so the suite stays portable.
            Assert.False(required,
                $"[{tag}] REQUIRED vendored fixture missing/empty: {path}. " +
                "Regenerate via DocxDiffBookmarkRealDocTests.__RegenerateVendoredFixture (remove its Skip).");
            _out.WriteLine($"[skip] optional fixture absent: {path}");
            return;
        }

        var leftBytes = File.ReadAllBytes(path);
        var left = new WmlDocument(path, leftBytes);
        var rightBytes = EditBookmarkAndReferenceParagraphs(leftBytes);
        var right = new WmlDocument(path, rightBytes);

        var result = DocxDiff.Compare(left, right);

        // emit artifacts for the LibreOffice oracle
        Directory.CreateDirectory(ScratchDir);
        File.WriteAllBytes(Path.Combine(ScratchDir, $"{tag}-left.docx"), leftBytes);
        File.WriteAllBytes(Path.Combine(ScratchDir, $"{tag}-right.docx"), rightBytes);
        File.WriteAllBytes(Path.Combine(ScratchDir, $"{tag}-compare.docx"), result.DocumentByteArray);

        // (1) schema validity — no NEW errors vs the inputs. Keys are PATH-INSENSITIVE (id + description, not
        // XPath): the diff legitimately relocates runs, so a PRE-EXISTING source quirk (the NVCA COI carries 65
        // <w:w w:val="0"> character-scale runs the strict validator rejects but Word tolerates) reappears at a
        // shifted run-path and must NOT count as new — it auto-excludes via baseErrors (the source carries the
        // identical error type). The duplicate-bookmark-id and numbering-order issues this campaign FIXED are
        // caught here; any new bookmark/field error would surface.
        var baseErrors = SchemaErrors(leftBytes).Concat(SchemaErrors(rightBytes)).ToHashSet();
        var newErrors = SchemaErrors(result.DocumentByteArray).Where(e => !baseErrors.Contains(e)).ToList();
        Assert.True(newErrors.Count == 0,
            $"[{tag}] Compare introduced {newErrors.Count} new schema error(s): {string.Join(" | ", newErrors.Take(6))}");

        // (2) bookmark-structure soundness of the Compare output: unique ids + 1:1 pairing
        var (startIds, endIds) = BookmarkIds(result.DocumentByteArray);
        Assert.True(startIds.Count == startIds.Distinct().Count(),
            $"[{tag}] duplicate bookmarkStart id(s): {Dup(startIds)}");
        Assert.True(endIds.Count == endIds.Distinct().Count(),
            $"[{tag}] duplicate bookmarkEnd id(s): {Dup(endIds)}");
        Assert.True(startIds.OrderBy(x => x).SequenceEqual(endIds.OrderBy(x => x)),
            $"[{tag}] bookmarkStart/End ids not 1:1 paired (starts:{startIds.Count} ends:{endIds.Count})");

        // (3) bookmark-structure round-trip: accept ≡ right, reject ≡ left (names + reference resolution)
        var accepted = RevisionProcessor.AcceptRevisions(result);
        var rejected = RevisionProcessor.RejectRevisions(result);

        // body-TEXT round-trip too (accept ≡ right, reject ≡ left): guards the noBreakHyphen/softHyphen/sym
        // char-accounting class of bug a bookmark/field-dense edit surfaces.
        Assert.Equal(BodyText(rightBytes), BodyText(accepted.DocumentByteArray));
        Assert.Equal(BodyText(leftBytes), BodyText(rejected.DocumentByteArray));
        _out.WriteLine($"[{tag}] bookmarks={startIds.Count} refs={Projection(rightBytes).RefCount} " +
            $"accept-dangling={Projection(AsBytes(accepted)).Dangling} reject-dangling={Projection(AsBytes(rejected)).Dangling}");
        File.WriteAllText(Path.Combine(ScratchDir, $"{tag}-proj-right.txt"), Projection(rightBytes).Signature);
        File.WriteAllText(Path.Combine(ScratchDir, $"{tag}-proj-accept.txt"), Projection(AsBytes(accepted)).Signature);
        File.WriteAllText(Path.Combine(ScratchDir, $"{tag}-proj-left.txt"), Projection(leftBytes).Signature);
        File.WriteAllText(Path.Combine(ScratchDir, $"{tag}-proj-reject.txt"), Projection(AsBytes(rejected)).Signature);
        Assert.Equal(Projection(rightBytes).Signature, Projection(AsBytes(accepted)).Signature);
        Assert.Equal(Projection(leftBytes).Signature, Projection(AsBytes(rejected)).Signature);

        // every internal reference in the Compare output resolves to a present bookmark name (no dangling)
        Assert.Equal(0, Projection(result.DocumentByteArray).Dangling);

        // (4) footnote/endnote real-doc oracles — formerly only reachable via the hard-coded ~/Downloads NVCA
        // path; they now run headlessly on every build over the vendored fixture (which carries footnotes, a
        // note-in-note reference, and endnotes), and additionally over the much denser NVCA docs when present.
        if (HasNotes(leftBytes, footnotes: true))
            AssertNoteFidelity(leftBytes, rightBytes, result, tag, footnotes: true);
        if (HasNotes(leftBytes, footnotes: false))
            AssertNoteFidelity(leftBytes, rightBytes, result, tag, footnotes: false);
    }

    /// <summary>Footnote (or endnote) id↔reference↔text round-trip + uniqueness + resolvability over a real doc.
    /// Mirrors the synthetic <see cref="DocxDiffFootnoteRobustnessTests"/> oracles but on a vendored/real fixture:
    /// unique note ids, every body/nested reference resolves, and referenced note TEXT round-trips
    /// (accept ≡ right, reject ≡ left).</summary>
    private void AssertNoteFidelity(byte[] leftBytes, byte[] rightBytes, WmlDocument result, string tag, bool footnotes)
    {
        var accepted = RevisionProcessor.AcceptRevisions(result);
        var rejected = RevisionProcessor.RejectRevisions(result);
        var kind = footnotes ? "footnote" : "endnote";

        // unique note ids in the Compare output (renumber must not collide reserved/real ids)
        var ids = NoteIds(result.DocumentByteArray, footnotes);
        Assert.True(ids.Count == ids.Distinct().Count(),
            $"[{tag}] duplicate {kind} definition id(s): {string.Join(",", ids.GroupBy(x => x).Where(g => g.Count() > 1).Select(g => g.Key))}");

        // no unresolved references anywhere (body AND inside note definitions — the note-in-note case)
        Assert.Equal(new List<string>(), UnresolvedNoteRefs(result.DocumentByteArray, footnotes));
        Assert.Equal(new List<string>(), UnresolvedNoteRefs(AsBytes(accepted), footnotes));
        Assert.Equal(new List<string>(), UnresolvedNoteRefs(AsBytes(rejected), footnotes));

        // referenced note TEXT round-trips: accept ≡ right's referenced notes, reject ≡ left's
        Assert.Equal(ReferencedNoteTexts(rightBytes, footnotes), ReferencedNoteTexts(AsBytes(accepted), footnotes));
        Assert.Equal(ReferencedNoteTexts(leftBytes, footnotes), ReferencedNoteTexts(AsBytes(rejected), footnotes));
        _out.WriteLine($"[{tag}] {kind}s: ids={ids.Count} referenced={ReferencedNoteTexts(rightBytes, footnotes).Count}");
    }

    /// <summary>Regenerate the vendored dense fixture from <see cref="DocxDiffRealDocFixture"/>. Skip-by-default —
    /// remove the Skip to rewrite the committed artifact, then restore it. (We keep the binary in the repo so CI
    /// runs against an exact, reviewable artifact; this fact is the documented, reproducible way to refresh it.)</summary>
    [Fact(Skip = "manual: regenerates the committed TestFiles/DD/DD001 fixture from DocxDiffRealDocFixture")]
    public void __RegenerateVendoredFixture()
    {
        var bytes = DocxDiffRealDocFixture.Build();
        Directory.CreateDirectory(Path.GetDirectoryName(VendoredFixturePath)!);
        File.WriteAllBytes(VendoredFixturePath, bytes);
        _out.WriteLine($"wrote {bytes.Length} bytes -> {VendoredFixturePath}");
    }

    // ---- variant construction -------------------------------------------------------------------

    /// <summary>Edit many bookmark-BEARING and bookmark-REFERENCING body paragraphs (append a sentinel word to a
    /// text run of each), AND edit a handful of footnote/endnote DEFINITION bodies — producing a real diff over the
    /// exact paragraphs that carry bookmark markers and REF/PAGEREF fields AND over note CONTENT. The note edits are
    /// deliberate: without them the notes would be byte-identical left↔right, so the IR note-DIFF path would never
    /// run and <see cref="AssertNoteFidelity"/>'s referenced-note-text round-trip would pass trivially. With them,
    /// <c>accept</c> must reproduce the edited note text and <c>reject</c> the original — a positive guard on
    /// note-content diff fidelity (the gap a pre-PR review flagged in the ratchet's coverage).</summary>
    private static byte[] EditBookmarkAndReferenceParagraphs(byte[] bytes)
    {
        using var ms = new MemoryStream();
        ms.Write(bytes, 0, bytes.Length);
        ms.Position = 0;
        using (var doc = WordprocessingDocument.Open(ms, true))
        {
            var body = doc.MainDocumentPart!.Document!.Body!;
            int bk = 0, rf = 0;
            foreach (var p in body.Descendants<Paragraph>())
            {
                bool carriesBookmark = p.Descendants<BookmarkStart>().Any();
                bool carriesRef = p.Descendants<FieldCode>().Any(fc =>
                    Regex.IsMatch(fc.Text ?? "", @"\b(REF|PAGEREF|NOTEREF)\b"));
                if (!carriesBookmark && !carriesRef) continue;
                // edit the first visible text run of the paragraph (skip field-internal display runs is fine —
                // any real text change makes a diff). Cap the count so the run stays fast but representative.
                var t = p.Descendants<Text>().FirstOrDefault(x => x.Text.Trim().Length > 3);
                if (t == null) continue;
                if (carriesBookmark && bk >= 40 && carriesRef && rf >= 40) continue;
                t.Text = t.Text + " (amended)";
                if (carriesBookmark) bk++;
                if (carriesRef) rf++;
            }

            // edit note CONTENT too (footnotes + endnotes) so the note-diff path is positively exercised
            EditNoteDefinitions(doc.MainDocumentPart!.FootnotesPart?.Footnotes);
            EditNoteDefinitions(doc.MainDocumentPart!.EndnotesPart?.Endnotes);
        }
        return ms.ToArray();
    }

    /// <summary>Append a sentinel to the first substantial text run of each REAL (non-reserved) note definition, so
    /// the variant differs from the source INSIDE the notes. Caps at a handful for speed.</summary>
    private static void EditNoteDefinitions(OpenXmlElement? notesRoot)
    {
        if (notesRoot == null) return;
        int n = 0;
        foreach (var def in notesRoot.Elements().Where(e => e.LocalName is "footnote" or "endnote"))
        {
            if (Attr(def, "type").Length != 0) continue; // skip separator / continuationSeparator
            var t = def.Descendants<Text>().FirstOrDefault(x => x.Text.Trim().Length > 3);
            if (t == null) continue;
            t.Text += " (note amended)";
            if (++n >= 8) break;
        }
    }

    // ---- observers ------------------------------------------------------------------------------

    private static byte[] AsBytes(WmlDocument d) => d.DocumentByteArray;

    private static string BodyText(byte[] bytes)
    {
        using var ms = new MemoryStream(bytes);
        using var w = WordprocessingDocument.Open(ms, false);
        var body = w.MainDocumentPart?.Document?.Body;
        return body is null ? "" : string.Concat(body.Descendants<Text>().Select(t => t.Text));
    }

    private static (List<int> Starts, List<int> Ends) BookmarkIds(byte[] bytes)
    {
        using var ms = new MemoryStream(bytes);
        using var w = WordprocessingDocument.Open(ms, false);
        var body = w.MainDocumentPart?.Document?.Body;
        var s = new List<int>();
        var e = new List<int>();
        if (body != null)
        {
            foreach (var b in body.Descendants().Where(x => x.LocalName == "bookmarkStart"))
                if (int.TryParse(Attr(b, "id"), out var v)) s.Add(v);
            foreach (var b in body.Descendants().Where(x => x.LocalName == "bookmarkEnd"))
                if (int.TryParse(Attr(b, "id"), out var v)) e.Add(v);
        }
        return (s, e);
    }

    private record Proj(string Signature, int RefCount, int Dangling);

    /// <summary>Bookmark/reference structural projection: sorted bookmark name set + each internal reference's
    /// (kind,target,resolves) triple. Equal projections ⇒ equal bookmark/cross-reference structure.</summary>
    private static Proj Projection(byte[] bytes)
    {
        using var ms = new MemoryStream(bytes);
        using var w = WordprocessingDocument.Open(ms, false);
        var body = w.MainDocumentPart?.Document?.Body;
        if (body == null) return new Proj("", 0, 0);

        var names = body.Descendants().Where(e => e.LocalName == "bookmarkStart")
            .Select(e => Attr(e, "name")).Where(n => n.Length > 0)
            .Distinct().OrderBy(n => n, StringComparer.Ordinal).ToList();
        var nameSet = new HashSet<string>(names);

        var refs = InternalRefs(body).ToList();
        int dangling = refs.Count(r => !nameSet.Contains(r.Target));
        var refSig = refs.Select(r => $"{r.Kind}:{r.Target}:{(nameSet.Contains(r.Target) ? "ok" : "X")}")
            .OrderBy(s => s, StringComparer.Ordinal);
        return new Proj($"N[{string.Join(",", names)}]R[{string.Join(",", refSig)}]", refs.Count, dangling);
    }

    private record Ref(string Kind, string Target);

    private static IEnumerable<Ref> InternalRefs(OpenXmlElement body)
    {
        var list = new List<Ref>();
        foreach (var h in body.Descendants<Hyperlink>())
            if (!string.IsNullOrEmpty(h.Anchor?.Value)) list.Add(new Ref("anchor", h.Anchor!.Value!));
        foreach (var f in body.Descendants<SimpleField>())
            if (Parse(f.Instruction?.Value ?? "") is { } t) list.Add(t);
        var instr = "";
        foreach (var e in body.Descendants().Where(x => x.LocalName is "fldChar" or "instrText" or "delInstrText"))
        {
            if (e.LocalName == "fldChar")
            {
                var ty = Attr(e, "fldCharType");
                if (ty == "begin") instr = "";
                else if (ty is "separate" or "end") { if (Parse(instr) is { } t) list.Add(t); instr = ""; }
            }
            else instr += e.InnerText;
        }
        return list;
    }

    private static Ref? Parse(string instr)
    {
        var toks = Regex.Matches(instr.Trim(), "\"[^\"]*\"|\\S+").Select(m => m.Value).ToList();
        if (toks.Count == 0) return null;
        var kw = toks[0].ToUpperInvariant();
        if (kw is "REF" or "PAGEREF" or "NOTEREF") return toks.Count >= 2 ? new Ref(kw, toks[1].Trim('"')) : null;
        if (kw == "HYPERLINK")
            for (int i = 1; i < toks.Count - 1; i++)
                if (toks[i] == "\\l") return new Ref("HYPERLINK\\l", toks[i + 1].Trim('"'));
        return null;
    }

    private static string Attr(OpenXmlElement e, string n) =>
        e.GetAttributes().FirstOrDefault(a => a.LocalName == n).Value ?? "";

    // ---- footnote / endnote observers (footnotes=true → footnotes part; false → endnotes part) ----

    private static OpenXmlElement? NotesRoot(WordprocessingDocument w, bool footnotes) => footnotes
        ? w.MainDocumentPart?.FootnotesPart?.Footnotes
        : w.MainDocumentPart?.EndnotesPart?.Endnotes;

    private static bool HasNotes(byte[] bytes, bool footnotes)
    {
        using var ms = new MemoryStream(bytes);
        using var w = WordprocessingDocument.Open(ms, false);
        var defName = footnotes ? "footnote" : "endnote";
        // a real (non-reserved) note definition: reserved separator/continuationSeparator carry a w:type attr
        return NotesRoot(w, footnotes)?.Descendants()
            .Any(e => e.LocalName == defName && Attr(e, "type").Length == 0) ?? false;
    }

    private static List<long> NoteIds(byte[] bytes, bool footnotes)
    {
        using var ms = new MemoryStream(bytes);
        using var w = WordprocessingDocument.Open(ms, false);
        var defName = footnotes ? "footnote" : "endnote";
        var ids = new List<long>();
        foreach (var d in NotesRoot(w, footnotes)?.Descendants().Where(e => e.LocalName == defName)
                          ?? Enumerable.Empty<OpenXmlElement>())
            if (long.TryParse(Attr(d, "id"), out var v)) ids.Add(v);
        return ids;
    }

    /// <summary>Referenced note TEXT in body order: for each body note-reference, the resolved definition's text.</summary>
    private static List<string> ReferencedNoteTexts(byte[] bytes, bool footnotes)
    {
        using var ms = new MemoryStream(bytes);
        using var w = WordprocessingDocument.Open(ms, false);
        var refName = footnotes ? "footnoteReference" : "endnoteReference";
        var defName = footnotes ? "footnote" : "endnote";
        var defs = new Dictionary<string, string>();
        foreach (var d in NotesRoot(w, footnotes)?.Descendants().Where(e => e.LocalName == defName)
                          ?? Enumerable.Empty<OpenXmlElement>())
            defs[Attr(d, "id")] = string.Concat(d.Descendants<Text>().Select(t => t.Text));
        var body = w.MainDocumentPart?.Document?.Body;
        var texts = new List<string>();
        if (body != null)
            foreach (var r in body.Descendants().Where(e => e.LocalName == refName))
                texts.Add(defs.TryGetValue(Attr(r, "id"), out var t) ? t : "(missing)");
        return texts;
    }

    /// <summary>Note-reference ids — in the body AND inside note definitions (note-in-note) — that fail to resolve
    /// to a definition. Empty list ⇒ every reference is resolvable.</summary>
    private static List<string> UnresolvedNoteRefs(byte[] bytes, bool footnotes)
    {
        using var ms = new MemoryStream(bytes);
        using var w = WordprocessingDocument.Open(ms, false);
        var refName = footnotes ? "footnoteReference" : "endnoteReference";
        var defName = footnotes ? "footnote" : "endnote";
        var root = NotesRoot(w, footnotes);
        var defIds = new HashSet<string>(
            (root?.Descendants().Where(e => e.LocalName == defName) ?? Enumerable.Empty<OpenXmlElement>())
            .Select(d => Attr(d, "id")));
        var scopes = new List<OpenXmlElement>();
        if (root != null) scopes.Add(root);                     // note-in-note references
        var body = w.MainDocumentPart?.Document?.Body;
        if (body != null) scopes.Add(body);                     // body references
        var bad = new List<string>();
        foreach (var scope in scopes)
            foreach (var r in scope.Descendants().Where(e => e.LocalName == refName))
            {
                var id = Attr(r, "id");
                if (!defIds.Contains(id)) bad.Add(id.Length == 0 ? "(null)" : id);
            }
        return bad;
    }

    private static string Dup(List<int> ids) =>
        string.Join(",", ids.GroupBy(x => x).Where(g => g.Count() > 1).Select(g => g.Key));

    private static HashSet<string> SchemaErrors(byte[] bytes)
    {
        using var ms = new MemoryStream(bytes);
        using var w = WordprocessingDocument.Open(ms, false);
        var v = new OpenXmlValidator(FileFormatVersions.Office2019);
        // Key = TYPE + PART + value-normalized DESCRIPTION (no XPath: the diff relocates runs, so a pre-existing
        // source error must match input↔output by type/part, not absolute position). Numeric ids are normalized
        // out of the description ('5' -> '#') so a LEGITIMATE footnote/endnote/bookmark RENUMBER — which changes
        // the value a pre-existing error names — still dedups. The motivating case: the SDK's
        // Sem_MissingReferenceElement is a documented FALSE POSITIVE on a note-in-note footnoteReference (it is
        // reported even when the target footnote exists; see docs/ooxml_corner_cases.md). When the engine
        // correctly compacts a gapped note id (5 -> 4) the error's value follows, and without normalization the
        // input copy ('5') and output copy ('4') would not match, mis-counting a non-defect as a NEW error.
        // PART stays in the key so a genuinely new dangling reference in a DIFFERENT part is still surfaced; and
        // body/note/bookmark reference resolvability is independently guarded by the BookmarkIds, Projection
        // .Dangling, and UnresolvedNoteRefs oracles, which do not rely on the SDK validator at all.
        return v.Validate(w)
            .Select(e => $"{e.Id}@{e.Part?.Uri}: {Regex.Replace(e.Description, "'[0-9]+'", "'#'")}")
            .ToHashSet();
    }
}
