#nullable enable

using System.IO;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;

namespace Docxodus.Tests;

/// <summary>
/// Deterministic builder for the vendored dense bookmark / cross-reference / footnote / endnote fixture
/// (<c>TestFiles/DD/DD001-DenseBookmarkXrefFootnote.docx</c>). This is the in-repo, license-clean,
/// reproducible source-of-truth for that committed artifact: it shapes a small Series-A-style legal
/// document the way a real contract does — bookmarked defined terms and sections, REF/PAGEREF/NOTEREF
/// fields and an internal hyperlink anchor pointing back at them, footnotes (one of which cites another
/// footnote — a note-in-note reference), endnotes, and intentionally non-sequential footnote ids — so the
/// structural id↔name↔reference, body-text round-trip, and schema-validity oracles in
/// <see cref="DocxDiffBookmarkRealDocTests"/> run on every build without depending on any machine-local file.
/// <para>The committed .docx is regenerated by <c>DocxDiffBookmarkRealDocTests.__RegenerateVendoredFixture</c>
/// (a Skip-by-default fact). Keep this builder and that file in sync.</para>
/// </summary>
public static class DocxDiffRealDocFixture
{
    private const string W = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
    private const string R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";

    /// <summary>Build the dense fixture as in-memory DOCX bytes. Deterministic (no timestamps in content).</summary>
    public static byte[] Build()
    {
        using var ms = new MemoryStream();
        using (var doc = WordprocessingDocument.Create(ms, WordprocessingDocumentType.Document))
        {
            var main = doc.AddMainDocumentPart();

            WritePartXml(main.AddNewPart<StyleDefinitionsPart>(), StylesXml());

            WritePartXml(main.AddNewPart<DocumentSettingsPart>(),
                $"<w:settings xmlns:w=\"{W}\"><w:footnotePr><w:numFmt w:val=\"decimal\"/></w:footnotePr>" +
                "<w:endnotePr><w:numFmt w:val=\"lowerRoman\"/></w:endnotePr></w:settings>");

            WritePartXml(main.AddNewPart<FootnotesPart>(), FootnotesXml());
            WritePartXml(main.AddNewPart<EndnotesPart>(), EndnotesXml());
            WritePartXml(main, DocumentXml());
        }
        return ms.ToArray();
    }

    // ---- styles ---------------------------------------------------------------------------------

    private static string StylesXml() =>
        $"<w:styles xmlns:w=\"{W}\">" +
        "<w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii=\"Times New Roman\" w:hAnsi=\"Times New Roman\"/>" +
        "<w:sz w:val=\"24\"/><w:szCs w:val=\"24\"/></w:rPr></w:rPrDefault></w:docDefaults>" +
        "<w:style w:type=\"paragraph\" w:default=\"1\" w:styleId=\"Normal\"><w:name w:val=\"Normal\"/></w:style>" +
        "<w:style w:type=\"paragraph\" w:styleId=\"Heading1\"><w:name w:val=\"heading 1\"/>" +
        "<w:basedOn w:val=\"Normal\"/><w:pPr><w:outlineLvl w:val=\"0\"/></w:pPr>" +
        "<w:rPr><w:b/><w:sz w:val=\"28\"/></w:rPr></w:style>" +
        "<w:style w:type=\"paragraph\" w:styleId=\"Heading2\"><w:name w:val=\"heading 2\"/>" +
        "<w:basedOn w:val=\"Normal\"/><w:pPr><w:outlineLvl w:val=\"1\"/></w:pPr>" +
        "<w:rPr><w:b/><w:sz w:val=\"26\"/></w:rPr></w:style>" +
        "<w:style w:type=\"paragraph\" w:styleId=\"FootnoteText\"><w:name w:val=\"footnote text\"/>" +
        "<w:basedOn w:val=\"Normal\"/><w:rPr><w:sz w:val=\"20\"/></w:rPr></w:style>" +
        "<w:style w:type=\"paragraph\" w:styleId=\"EndnoteText\"><w:name w:val=\"endnote text\"/>" +
        "<w:basedOn w:val=\"Normal\"/><w:rPr><w:sz w:val=\"20\"/></w:rPr></w:style>" +
        "<w:style w:type=\"character\" w:styleId=\"Hyperlink\"><w:name w:val=\"Hyperlink\"/>" +
        "<w:rPr><w:color w:val=\"0563C1\"/><w:u w:val=\"single\"/></w:rPr></w:style>" +
        "<w:style w:type=\"character\" w:styleId=\"FootnoteReference\"><w:name w:val=\"footnote reference\"/>" +
        "<w:rPr><w:vertAlign w:val=\"superscript\"/></w:rPr></w:style>" +
        "<w:style w:type=\"character\" w:styleId=\"EndnoteReference\"><w:name w:val=\"endnote reference\"/>" +
        "<w:rPr><w:vertAlign w:val=\"superscript\"/></w:rPr></w:style>" +
        "</w:styles>";

    // ---- footnotes (intentionally non-sequential ids 1,2,3,5; fn2 cites fn5 — note-in-note) ------

    private static string FootnotesXml() =>
        $"<w:footnotes xmlns:w=\"{W}\">" +
        "<w:footnote w:type=\"separator\" w:id=\"-1\"><w:p><w:r><w:separator/></w:r></w:p></w:footnote>" +
        "<w:footnote w:type=\"continuationSeparator\" w:id=\"0\"><w:p><w:r><w:continuationSeparator/></w:r></w:p></w:footnote>" +
        "<w:footnote w:id=\"1\"><w:p><w:pPr><w:pStyle w:val=\"FootnoteText\"/></w:pPr>" +
        "<w:r><w:rPr><w:rStyle w:val=\"FootnoteReference\"/></w:rPr><w:footnoteRef/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\"> Capitalized terms are defined in Article I of this Agreement.</w:t></w:r></w:p></w:footnote>" +
        "<w:footnote w:id=\"2\"><w:p><w:pPr><w:pStyle w:val=\"FootnoteText\"/></w:pPr>" +
        "<w:r><w:rPr><w:rStyle w:val=\"FootnoteReference\"/></w:rPr><w:footnoteRef/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\"> The transfer restrictions survive the Closing; see also note </w:t></w:r>" +
        "<w:r><w:rPr><w:rStyle w:val=\"FootnoteReference\"/></w:rPr><w:footnoteReference w:id=\"5\"/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\"> below.</w:t></w:r></w:p></w:footnote>" +
        "<w:footnote w:id=\"3\"><w:p><w:pPr><w:pStyle w:val=\"FootnoteText\"/></w:pPr>" +
        "<w:r><w:rPr><w:rStyle w:val=\"FootnoteReference\"/></w:rPr><w:footnoteRef/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\"> Each Purchaser severally and not jointly makes the foregoing representation.</w:t></w:r></w:p></w:footnote>" +
        "<w:footnote w:id=\"5\"><w:p><w:pPr><w:pStyle w:val=\"FootnoteText\"/></w:pPr>" +
        "<w:r><w:rPr><w:rStyle w:val=\"FootnoteReference\"/></w:rPr><w:footnoteRef/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\"> Affiliate transfers remain subject to the right of first refusal in Section 4.2.</w:t></w:r></w:p></w:footnote>" +
        "</w:footnotes>";

    private static string EndnotesXml() =>
        $"<w:endnotes xmlns:w=\"{W}\">" +
        "<w:endnote w:type=\"separator\" w:id=\"-1\"><w:p><w:r><w:separator/></w:r></w:p></w:endnote>" +
        "<w:endnote w:type=\"continuationSeparator\" w:id=\"0\"><w:p><w:r><w:continuationSeparator/></w:r></w:p></w:endnote>" +
        "<w:endnote w:id=\"1\"><w:p><w:pPr><w:pStyle w:val=\"EndnoteText\"/></w:pPr>" +
        "<w:r><w:rPr><w:rStyle w:val=\"EndnoteReference\"/></w:rPr><w:endnoteRef/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\"> Schedule A lists the authorized and outstanding capital stock as of the date hereof.</w:t></w:r></w:p></w:endnote>" +
        "<w:endnote w:id=\"2\"><w:p><w:pPr><w:pStyle w:val=\"EndnoteText\"/></w:pPr>" +
        "<w:r><w:rPr><w:rStyle w:val=\"EndnoteReference\"/></w:rPr><w:endnoteRef/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\"> Notices are deemed given upon confirmed electronic delivery.</w:t></w:r></w:p></w:endnote>" +
        "</w:endnotes>";

    // ---- document body --------------------------------------------------------------------------

    private static string DocumentXml() =>
        $"<w:document xmlns:w=\"{W}\" xmlns:r=\"{R}\"><w:body>" +

        // Title
        "<w:p><w:pPr><w:pStyle w:val=\"Heading1\"/></w:pPr>" +
        "<w:bookmarkStart w:id=\"1\" w:name=\"_Toc_Title\"/>" +
        "<w:r><w:t xml:space=\"preserve\">Series A Preferred Stock Purchase Agreement</w:t></w:r>" +
        "<w:bookmarkEnd w:id=\"1\"/></w:p>" +

        // Article I — Definitions
        "<w:p><w:pPr><w:pStyle w:val=\"Heading1\"/></w:pPr>" +
        "<w:bookmarkStart w:id=\"2\" w:name=\"_Ref_Definitions\"/>" +
        "<w:r><w:t xml:space=\"preserve\">Article I. Definitions</w:t></w:r>" +
        "<w:bookmarkEnd w:id=\"2\"/></w:p>" +

        "<w:p><w:r><w:t xml:space=\"preserve\">As used herein, the term </w:t></w:r>" +
        "<w:bookmarkStart w:id=\"3\" w:name=\"_Ref_DefAffiliate\"/>" +
        "<w:r><w:rPr><w:b/></w:rPr><w:t xml:space=\"preserve\">Affiliate</w:t></w:r>" +
        "<w:bookmarkEnd w:id=\"3\"/>" +
        "<w:r><w:t xml:space=\"preserve\"> means any person controlling, controlled by, or under common control with the Company.</w:t></w:r></w:p>" +

        "<w:p><w:r><w:t xml:space=\"preserve\">The term </w:t></w:r>" +
        "<w:bookmarkStart w:id=\"4\" w:name=\"_Ref_DefClosing\"/>" +
        "<w:r><w:rPr><w:b/></w:rPr><w:t xml:space=\"preserve\">Closing</w:t></w:r>" +
        "<w:bookmarkEnd w:id=\"4\"/>" +
        "<w:r><w:t xml:space=\"preserve\"> means the consummation of the purchase and sale of the Securities hereunder.</w:t></w:r></w:p>" +

        "<w:p><w:r><w:t xml:space=\"preserve\">The term </w:t></w:r>" +
        "<w:bookmarkStart w:id=\"5\" w:name=\"_Ref_DefSecurities\"/>" +
        "<w:r><w:rPr><w:b/></w:rPr><w:t xml:space=\"preserve\">Securities</w:t></w:r>" +
        "<w:bookmarkEnd w:id=\"5\"/>" +
        "<w:r><w:t xml:space=\"preserve\"> means the shares of Series A Preferred Stock being issued and sold under this Agreement.</w:t></w:r></w:p>" +

        // Article II — Purchase and Sale (REF + PAGEREF + footnote ref bookmarked for NOTEREF)
        "<w:p><w:pPr><w:pStyle w:val=\"Heading1\"/></w:pPr>" +
        "<w:bookmarkStart w:id=\"6\" w:name=\"_Ref_Sec2\"/>" +
        "<w:r><w:t xml:space=\"preserve\">Article II. Purchase and Sale</w:t></w:r>" +
        "<w:bookmarkEnd w:id=\"6\"/></w:p>" +

        "<w:p><w:r><w:t xml:space=\"preserve\">Subject to the terms hereof, each Purchaser agrees to purchase the Securities from any </w:t></w:r>" +
        RefField("REF", "_Ref_DefAffiliate", "Affiliate") +
        "<w:r><w:t xml:space=\"preserve\"> of the Company</w:t></w:r>" +
        "<w:bookmarkStart w:id=\"7\" w:name=\"_Ref_FnMark1\"/>" +
        "<w:r><w:rPr><w:rStyle w:val=\"FootnoteReference\"/></w:rPr><w:footnoteReference w:id=\"1\"/></w:r>" +
        "<w:bookmarkEnd w:id=\"7\"/>" +
        "<w:r><w:t xml:space=\"preserve\"> in accordance with this Article II.</w:t></w:r></w:p>" +

        "<w:p><w:r><w:t xml:space=\"preserve\">The definition of the Securities appears on page </w:t></w:r>" +
        RefField("PAGEREF", "_Ref_DefSecurities", "4") +
        "<w:r><w:t xml:space=\"preserve\"> of this Agreement.</w:t></w:r></w:p>" +

        // Article III — Closing (NOTEREF + internal hyperlink anchor + fn + en refs)
        "<w:p><w:pPr><w:pStyle w:val=\"Heading1\"/></w:pPr>" +
        "<w:bookmarkStart w:id=\"8\" w:name=\"_Ref_Sec3\"/>" +
        "<w:r><w:t xml:space=\"preserve\">Article III. Closing</w:t></w:r>" +
        "<w:bookmarkEnd w:id=\"8\"/></w:p>" +

        "<w:p><w:r><w:t xml:space=\"preserve\">The transfer restrictions described in note </w:t></w:r>" +
        RefField("NOTEREF", "_Ref_FnMark1", "1") +
        "<w:r><w:t xml:space=\"preserve\"> apply at the </w:t></w:r>" +
        "<w:hyperlink w:anchor=\"_Ref_DefClosing\"><w:r><w:rPr><w:rStyle w:val=\"Hyperlink\"/></w:rPr>" +
        "<w:t xml:space=\"preserve\">Closing</w:t></w:r></w:hyperlink>" +
        "<w:r><w:t xml:space=\"preserve\"> of the transactions</w:t></w:r>" +
        "<w:r><w:rPr><w:rStyle w:val=\"FootnoteReference\"/></w:rPr><w:footnoteReference w:id=\"2\"/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\"> contemplated hereby</w:t></w:r>" +
        "<w:r><w:rPr><w:rStyle w:val=\"EndnoteReference\"/></w:rPr><w:endnoteReference w:id=\"1\"/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\">.</w:t></w:r></w:p>" +

        "<w:p><w:r><w:t xml:space=\"preserve\">Each Purchaser confirms the representations of this Article III</w:t></w:r>" +
        "<w:r><w:rPr><w:rStyle w:val=\"FootnoteReference\"/></w:rPr><w:footnoteReference w:id=\"3\"/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\"> are true and correct as of the Closing.</w:t></w:r></w:p>" +

        // Article IV — Miscellaneous (REF/PAGEREF back-references + fn5 + en2)
        "<w:p><w:pPr><w:pStyle w:val=\"Heading1\"/></w:pPr>" +
        "<w:bookmarkStart w:id=\"9\" w:name=\"_Ref_Sec4\"/>" +
        "<w:r><w:t xml:space=\"preserve\">Article IV. Miscellaneous</w:t></w:r>" +
        "<w:bookmarkEnd w:id=\"9\"/></w:p>" +

        "<w:p><w:r><w:t xml:space=\"preserve\">The obligations under </w:t></w:r>" +
        RefField("REF", "_Ref_Sec2", "Article II") +
        "<w:r><w:t xml:space=\"preserve\"> and the definitions in </w:t></w:r>" +
        RefField("REF", "_Ref_Definitions", "Article I") +
        "<w:r><w:t xml:space=\"preserve\"> survive the Closing described at page </w:t></w:r>" +
        RefField("PAGEREF", "_Ref_Sec3", "6") +
        "<w:r><w:t xml:space=\"preserve\">, including any Affiliate transfer</w:t></w:r>" +
        "<w:r><w:rPr><w:rStyle w:val=\"FootnoteReference\"/></w:rPr><w:footnoteReference w:id=\"5\"/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\"> permitted hereunder.</w:t></w:r></w:p>" +

        "<w:p><w:r><w:t xml:space=\"preserve\">Capitalization and notice provisions are set forth in </w:t></w:r>" +
        "<w:bookmarkStart w:id=\"10\" w:name=\"_Ref_Schedule\"/>" +
        "<w:r><w:rPr><w:b/></w:rPr><w:t xml:space=\"preserve\">Schedule A</w:t></w:r>" +
        "<w:bookmarkEnd w:id=\"10\"/>" +
        "<w:r><w:t xml:space=\"preserve\"> hereto</w:t></w:r>" +
        "<w:r><w:rPr><w:rStyle w:val=\"EndnoteReference\"/></w:rPr><w:endnoteReference w:id=\"2\"/></w:r>" +
        "<w:r><w:t xml:space=\"preserve\">.</w:t></w:r></w:p>" +

        "<w:sectPr><w:pgSz w:w=\"12240\" w:h=\"15840\"/>" +
        "<w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\"/></w:sectPr>" +
        "</w:body></w:document>";

    /// <summary>A complete fldChar REF/PAGEREF/NOTEREF field with a separate-side display value.</summary>
    private static string RefField(string keyword, string target, string display) =>
        "<w:r><w:fldChar w:fldCharType=\"begin\"/></w:r>" +
        $"<w:r><w:instrText xml:space=\"preserve\"> {keyword} {target} \\h </w:instrText></w:r>" +
        "<w:r><w:fldChar w:fldCharType=\"separate\"/></w:r>" +
        $"<w:r><w:t xml:space=\"preserve\">{display}</w:t></w:r>" +
        "<w:r><w:fldChar w:fldCharType=\"end\"/></w:r>";

    private static void WritePartXml(OpenXmlPart part, string xml)
    {
        using var stream = part.GetStream(FileMode.Create, FileAccess.Write);
        using var writer = new StreamWriter(stream, new System.Text.UTF8Encoding(false));
        writer.Write(xml);
    }
}
